# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "Hanna Soderstrom"
__copyright__ = "Copyright 2023, Hanna Soderstrom"
__email__ = "hanna.soderstrom@gu.se"
__license__ = "GPL-3"

include: "rules/common.smk"
include: "rules/sentieon.smk"


rule all:
    input:
        unpack(compile_output_list),
