---

 resources: "resources.yaml"
 samples: "samples.tsv"
 units: "units.tsv"

 default_container: "docker://hydragenetics/common:0.1.9"

 sentieon: #NOTE Local path to container and paths inside container
   container: "/apps/bio/singularities/wgs_somatic/sentieon_peta_201911_hg38_new220503.simg" # What if hg19?
   reference: "/databases/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
   sentieon: "/sentieon-genomics-201911/bin/sentieon"
   mills: "/databases/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
   dbsnp: "/databases/Homo_sapiens_assembly38.dbsnp138.vcf.gz"
   tnscope_settings: "--min_init_normal_lod 0.5 --min_normal_lod 3.0 --min_init_tumor_lod 1.0 --min_tumor_lod 3 --trim_soft_clip"
   dnascope_settings: "--pcr_indel_model NONE"
   dbsnp: "/databases/Homo_sapiens_assembly38.dbsnp138.vcf.gz"
   dnascope_model: "/databases/SentieonDNAscopeModelBeta0.5.model"
